/**
 * Códigos estables para `response.data.code` (i18n en el front; message sigue en español por compatibilidad).
 */
export const EXCEL_ERR = {
  EXCEL_EXPORT_NO_TEMPLATE: "EXCEL_EXPORT_NO_TEMPLATE",
  EXCEL_EXPORT_TEMPLATE_INVALID: "EXCEL_EXPORT_TEMPLATE_INVALID",
  EXCEL_EXPORT_BUILD_FAILED: "EXCEL_EXPORT_BUILD_FAILED",
  EXCEL_IMPORT_NO_FILE: "EXCEL_IMPORT_NO_FILE",
  EXCEL_NO_TEMPLATE_FOR_IMPORT: "EXCEL_NO_TEMPLATE_FOR_IMPORT",
  EXCEL_READ_UPLOAD_FAILED: "EXCEL_READ_UPLOAD_FAILED",
  EXCEL_GET_IMPORT_NOT_FOUND: "EXCEL_GET_IMPORT_NOT_FOUND",
  EXCEL_IMPORT_PUBLISH_NOT_DRAFT: "EXCEL_IMPORT_PUBLISH_NOT_DRAFT",
  EXCEL_NO_TEMPLATE_FOR_PUBLISH: "EXCEL_NO_TEMPLATE_FOR_PUBLISH",
  EXCEL_NO_ROWS_TO_PUBLISH: "EXCEL_NO_ROWS_TO_PUBLISH",
  EXCEL_UNMATCHED_PUBLISH: "EXCEL_UNMATCHED_PUBLISH",
  EXCEL_KEY_COLLISION_PUBLISH: "EXCEL_KEY_COLLISION_PUBLISH",
  EXCEL_PARSE_WARNINGS_PUBLISH: "EXCEL_PARSE_WARNINGS_PUBLISH",
  EXCEL_WEEK_START_BAD: "EXCEL_WEEK_START_BAD",
  EXCEL_WEEK_START_REQUIRED: "EXCEL_WEEK_START_REQUIRED",
  EXCEL_WEEK_INVALID_QUERY: "EXCEL_WEEK_INVALID_QUERY",
  EXCEL_ADMIN_WEEK_NOT_PUBLISHED: "EXCEL_ADMIN_WEEK_NOT_PUBLISHED",
  EXCEL_DISCARD_NOT_FOUND: "EXCEL_DISCARD_NOT_FOUND",
} as const;

export type ExcelPlanningErrorCode =
  (typeof EXCEL_ERR)[keyof typeof EXCEL_ERR];
